-- =============================================================================
-- Materialized Views — Oracle Database 19c
-- Oracle-isms: BUILD IMMEDIATE, REFRESH ON DEMAND, ENABLE QUERY REWRITE,
--              DBMS_MVIEW.REFRESH, NVL, DECODE
-- =============================================================================

-- Inventory valuation summary by ABC class (refreshed nightly)
CREATE MATERIALIZED VIEW MFG.MV_INVENTORY_VALUATION
BUILD IMMEDIATE
REFRESH ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT p.ABC_CLASS,
       p.PART_TYPE,
       COUNT(DISTINCT p.PART_ID) AS PART_COUNT,
       NVL(SUM(inv.on_hand), 0) AS TOTAL_ON_HAND,
       NVL(SUM(inv.on_hand * p.CURRENT_COST), 0) AS TOTAL_VALUE,
       NVL(AVG(p.CURRENT_COST), 0) AS AVG_UNIT_COST
FROM   MFG.PART_MASTER p
LEFT JOIN (
    SELECT PART_ID, SUM(TXN_QTY) AS on_hand
    FROM   MFG.INVENTORY_TRANSACTIONS
    GROUP BY PART_ID
) inv ON p.PART_ID = inv.PART_ID
WHERE  p.STATUS = 'ACTIVE'
GROUP BY p.ABC_CLASS, p.PART_TYPE;

-- Supplier performance dashboard (refreshed weekly)
CREATE MATERIALIZED VIEW MFG.MV_SUPPLIER_PERFORMANCE
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT s.SUPPLIER_ID,
       s.SUPPLIER_CODE,
       s.SUPPLIER_NAME,
       COUNT(qi.INSPECTION_ID) AS INSPECTIONS_YTD,
       SUM(DECODE(qi.DISPOSITION, 'ACCEPTED', 1, 0)) AS ACCEPTED_COUNT,
       SUM(DECODE(qi.DISPOSITION, 'REJECTED', 1, 0)) AS REJECTED_COUNT,
       ROUND(
           SUM(DECODE(qi.DISPOSITION, 'ACCEPTED', 1, 0)) /
           GREATEST(COUNT(qi.INSPECTION_ID), 1) * 100, 2
       ) AS ACCEPTANCE_RATE_PCT,
       NVL(AVG(qi.DEFECTS_FOUND), 0) AS AVG_DEFECTS_PER_LOT,
       s.DEFECT_PPM,
       s.QUALITY_RATING,
       s.DELIVERY_RATING
FROM   MFG.SUPPLIER_MASTER s
LEFT JOIN MFG.QUALITY_INSPECTIONS qi
       ON s.SUPPLIER_ID = qi.SUPPLIER_ID
       AND qi.INSPECTION_DATE >= TRUNC(SYSDATE, 'YYYY')
GROUP BY s.SUPPLIER_ID, s.SUPPLIER_CODE, s.SUPPLIER_NAME,
         s.DEFECT_PPM, s.QUALITY_RATING, s.DELIVERY_RATING;

-- Warranty cost by defect code (refreshed monthly)
CREATE MATERIALIZED VIEW MFG.MV_WARRANTY_COST_ANALYSIS
BUILD IMMEDIATE
REFRESH ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT wc.DEFECT_CODE,
       DECODE(wc.WARRANTY_TYPE,
              'BW', 'Basic', 'PT', 'Powertrain',
              'EM', 'Emissions', 'CR', 'Corrosion') AS WARRANTY_DESC,
       COUNT(*) AS CLAIM_COUNT,
       SUM(NVL(wc.SETTLEMENT_AMT, 0)) AS TOTAL_SETTLEMENT,
       ROUND(AVG(NVL(wc.SETTLEMENT_AMT, 0)), 2) AS AVG_SETTLEMENT,
       MIN(wc.REPAIR_DATE) AS FIRST_OCCURRENCE,
       MAX(wc.REPAIR_DATE) AS LAST_OCCURRENCE,
       ROUND(AVG(NVL(wc.MILEAGE, 0)), 0) AS AVG_MILEAGE
FROM   MFG.WARRANTY_CLAIMS wc
WHERE  wc.DISPOSITION IN ('APPROVED', 'REJECTED')
GROUP BY wc.DEFECT_CODE, wc.WARRANTY_TYPE;

-- Production order backlog (refreshed daily)
CREATE MATERIALIZED VIEW MFG.MV_PRODUCTION_BACKLOG
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT po.PLANT_CODE,
       pl.PLANT_NAME,
       po.STATUS,
       COUNT(*) AS ORDER_COUNT,
       SUM(po.ORDER_QTY) AS TOTAL_QTY,
       SUM(po.ORDER_QTY - NVL(po.COMPLETED_QTY, 0)) AS REMAINING_QTY,
       MIN(po.DUE_DATE) AS EARLIEST_DUE,
       SUM(CASE WHEN po.DUE_DATE < SYSDATE AND po.STATUS != 'COMPLETED'
                THEN 1 ELSE 0 END) AS OVERDUE_COUNT
FROM   MFG.PRODUCTION_ORDERS po
JOIN   MFG.PLANT_MASTER pl ON po.PLANT_CODE = pl.PLANT_CODE
WHERE  po.STATUS NOT IN ('COMPLETED', 'CANCELLED')
GROUP BY po.PLANT_CODE, pl.PLANT_NAME, po.STATUS;
