-- =============================================================================
-- Oracle Manufacturing Schema — Automotive MES / Supply Chain / Warranty
-- Oracle Database 19c, Character Set AL32UTF8
-- =============================================================================

-- Sequences
CREATE SEQUENCE MFG.PART_SEQ         START WITH 100001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MFG.ORDER_SEQ        START WITH 500001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MFG.CLAIM_SEQ        START WITH 900001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MFG.INSPECTION_SEQ   START WITH 200001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MFG.SHIPMENT_SEQ     START WITH 300001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MFG.AUDIT_SEQ        START WITH 1      INCREMENT BY 1 NOCACHE;

-- Part Master
CREATE TABLE MFG.PART_MASTER (
    PART_ID            NUMBER(12)      NOT NULL,
    PART_NUMBER        VARCHAR2(20)    NOT NULL,
    DESCRIPTION        VARCHAR2(100),
    PART_TYPE          VARCHAR2(4)     NOT NULL,  -- RM/PU/MF/SA (Raw/Purchased/Manufactured/SubAssembly)
    UOM                VARCHAR2(6)     DEFAULT 'EA',
    WEIGHT_KG          NUMBER(8,3),
    STD_COST           NUMBER(12,4),
    CURRENT_COST       NUMBER(12,4),
    REORDER_POINT      NUMBER(10,2)    DEFAULT 0,
    REORDER_QTY        NUMBER(10,2)    DEFAULT 0,
    LEAD_TIME_DAYS     NUMBER(4)       DEFAULT 0,
    ABC_CLASS          VARCHAR2(1)     DEFAULT 'C',
    STATUS             VARCHAR2(10)    DEFAULT 'ACTIVE',
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    MODIFIED_DATE      DATE            DEFAULT SYSDATE,
    MODIFIED_BY        VARCHAR2(30)    DEFAULT USER,
    CONSTRAINT PK_PART_MASTER PRIMARY KEY (PART_ID),
    CONSTRAINT UK_PART_NUMBER UNIQUE (PART_NUMBER),
    CONSTRAINT CK_PART_TYPE CHECK (PART_TYPE IN ('RM','PU','MF','SA')),
    CONSTRAINT CK_ABC_CLASS CHECK (ABC_CLASS IN ('A','B','C'))
);

-- Bill of Materials
CREATE TABLE MFG.BILL_OF_MATERIALS (
    BOM_ID             NUMBER(12)      NOT NULL,
    PARENT_PART_ID     NUMBER(12)      NOT NULL,
    COMPONENT_PART_ID  NUMBER(12)      NOT NULL,
    QTY_PER_ASSEMBLY   NUMBER(8,4)     NOT NULL,
    SCRAP_FACTOR       NUMBER(5,4)     DEFAULT 0,
    EFFECTIVITY_START  DATE            NOT NULL,
    EFFECTIVITY_END    DATE,
    ITEM_TYPE          VARCHAR2(4)     DEFAULT 'STD',
    FIND_NUMBER        VARCHAR2(10),
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_BOM PRIMARY KEY (BOM_ID),
    CONSTRAINT FK_BOM_PARENT FOREIGN KEY (PARENT_PART_ID) REFERENCES MFG.PART_MASTER(PART_ID),
    CONSTRAINT FK_BOM_COMP FOREIGN KEY (COMPONENT_PART_ID) REFERENCES MFG.PART_MASTER(PART_ID)
);

-- Supplier Master
CREATE TABLE MFG.SUPPLIER_MASTER (
    SUPPLIER_ID        NUMBER(10)      NOT NULL,
    SUPPLIER_CODE      VARCHAR2(12)    NOT NULL,
    SUPPLIER_NAME      VARCHAR2(80)    NOT NULL,
    CONTACT_NAME       VARCHAR2(60),
    ADDRESS_LINE1      VARCHAR2(60),
    ADDRESS_LINE2      VARCHAR2(60),
    CITY               VARCHAR2(40),
    STATE_PROVINCE     VARCHAR2(30),
    POSTAL_CODE        VARCHAR2(15),
    COUNTRY_CODE       VARCHAR2(3)     DEFAULT 'USA',
    PHONE              VARCHAR2(20),
    EMAIL              VARCHAR2(80),
    PAYMENT_TERMS      VARCHAR2(10)    DEFAULT 'NET30',
    CURRENCY_CODE      VARCHAR2(3)     DEFAULT 'USD',
    QUALITY_RATING     NUMBER(3,1),
    DELIVERY_RATING    NUMBER(3,1),
    DEFECT_PPM         NUMBER(8),
    STATUS             VARCHAR2(10)    DEFAULT 'ACTIVE',
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT UK_SUPPLIER_CODE UNIQUE (SUPPLIER_CODE)
);

-- Production Orders
CREATE TABLE MFG.PRODUCTION_ORDERS (
    ORDER_ID           NUMBER(12)      NOT NULL,
    ORDER_NUMBER       VARCHAR2(15)    NOT NULL,
    PLANT_CODE         VARCHAR2(4)     NOT NULL,
    ASSEMBLY_PART_ID   NUMBER(12)      NOT NULL,
    ORDER_QTY          NUMBER(10,2)    NOT NULL,
    COMPLETED_QTY      NUMBER(10,2)    DEFAULT 0,
    SCRAP_QTY          NUMBER(10,2)    DEFAULT 0,
    ORDER_DATE         DATE            NOT NULL,
    DUE_DATE           DATE            NOT NULL,
    COMPLETION_DATE    DATE,
    STATUS             VARCHAR2(12)    DEFAULT 'PLANNED',
    PRIORITY           NUMBER(1)       DEFAULT 3,
    SHIFT_CODE         VARCHAR2(2),
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_PROD_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT UK_ORDER_NUMBER UNIQUE (ORDER_NUMBER),
    CONSTRAINT FK_ORDER_PART FOREIGN KEY (ASSEMBLY_PART_ID) REFERENCES MFG.PART_MASTER(PART_ID),
    CONSTRAINT CK_ORDER_STATUS CHECK (STATUS IN ('PLANNED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED'))
);

-- Inventory Transactions
CREATE TABLE MFG.INVENTORY_TRANSACTIONS (
    TXN_ID             NUMBER(15)      NOT NULL,
    PART_ID            NUMBER(12)      NOT NULL,
    TXN_TYPE           VARCHAR2(4)     NOT NULL,  -- RC/IS/AJ/TR (Receipt/Issue/Adjust/Transfer)
    TXN_QTY            NUMBER(10,2)    NOT NULL,
    TXN_COST           NUMBER(12,4),
    WAREHOUSE_CODE     VARCHAR2(6),
    LOCATION_CODE      VARCHAR2(10),
    REFERENCE_TYPE     VARCHAR2(4),
    REFERENCE_ID       NUMBER(12),
    TXN_DATE           DATE            DEFAULT SYSDATE,
    CREATED_BY         VARCHAR2(30)    DEFAULT USER,
    CONSTRAINT PK_INV_TXN PRIMARY KEY (TXN_ID),
    CONSTRAINT FK_INV_PART FOREIGN KEY (PART_ID) REFERENCES MFG.PART_MASTER(PART_ID),
    CONSTRAINT CK_TXN_TYPE CHECK (TXN_TYPE IN ('RC','IS','AJ','TR'))
);

-- Warranty Claims
CREATE TABLE MFG.WARRANTY_CLAIMS (
    CLAIM_ID           NUMBER(12)      NOT NULL,
    CLAIM_NUMBER       VARCHAR2(15)    NOT NULL,
    DEALER_CODE        VARCHAR2(8)     NOT NULL,
    VIN                VARCHAR2(17)    NOT NULL,
    PART_ID            NUMBER(12)      NOT NULL,
    WARRANTY_TYPE      VARCHAR2(2)     NOT NULL,  -- BW/PT/EM/CR
    DEFECT_CODE        VARCHAR2(6),
    REPAIR_DATE        DATE,
    MILEAGE            NUMBER(8),
    SALE_DATE          DATE,
    LABOR_HOURS        NUMBER(6,2),
    LABOR_RATE         NUMBER(8,2),
    PARTS_COST         NUMBER(10,2),
    SUBLET_COST        NUMBER(10,2),
    SETTLEMENT_AMT     NUMBER(12,2),
    DISPOSITION        VARCHAR2(12)    DEFAULT 'PENDING',
    PROCESS_DATE       DATE,
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_WARRANTY PRIMARY KEY (CLAIM_ID),
    CONSTRAINT UK_CLAIM_NUMBER UNIQUE (CLAIM_NUMBER),
    CONSTRAINT FK_CLAIM_PART FOREIGN KEY (PART_ID) REFERENCES MFG.PART_MASTER(PART_ID),
    CONSTRAINT CK_WARRANTY_TYPE CHECK (WARRANTY_TYPE IN ('BW','PT','EM','CR'))
);

-- Quality Inspections
CREATE TABLE MFG.QUALITY_INSPECTIONS (
    INSPECTION_ID      NUMBER(12)      NOT NULL,
    PART_ID            NUMBER(12)      NOT NULL,
    SUPPLIER_ID        NUMBER(10),
    LOT_NUMBER         VARCHAR2(20),
    SAMPLE_SIZE        NUMBER(6),
    DEFECTS_FOUND      NUMBER(6)       DEFAULT 0,
    DISPOSITION        VARCHAR2(12)    DEFAULT 'PENDING',
    INSPECTOR_ID       VARCHAR2(20),
    INSPECTION_DATE    DATE            DEFAULT SYSDATE,
    MEASUREMENT_1      NUMBER(9,4),
    MEASUREMENT_2      NUMBER(9,4),
    MEASUREMENT_3      NUMBER(9,4),
    UPPER_SPEC_LIMIT   NUMBER(9,4),
    LOWER_SPEC_LIMIT   NUMBER(9,4),
    CREATED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_INSPECTION PRIMARY KEY (INSPECTION_ID),
    CONSTRAINT FK_INSP_PART FOREIGN KEY (PART_ID) REFERENCES MFG.PART_MASTER(PART_ID),
    CONSTRAINT FK_INSP_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES MFG.SUPPLIER_MASTER(SUPPLIER_ID)
);

-- Plant Master
CREATE TABLE MFG.PLANT_MASTER (
    PLANT_CODE         VARCHAR2(4)     NOT NULL,
    PLANT_NAME         VARCHAR2(60)    NOT NULL,
    CITY               VARCHAR2(40),
    STATE_PROVINCE     VARCHAR2(30),
    COUNTRY_CODE       VARCHAR2(3)     DEFAULT 'USA',
    DAILY_CAPACITY     NUMBER(6),
    SHIFT_COUNT        NUMBER(1)       DEFAULT 2,
    STATUS             VARCHAR2(10)    DEFAULT 'ACTIVE',
    CONSTRAINT PK_PLANT PRIMARY KEY (PLANT_CODE)
);

-- Audit Trail
CREATE TABLE MFG.AUDIT_TRAIL (
    AUDIT_ID           NUMBER(15)      NOT NULL,
    TABLE_NAME         VARCHAR2(30)    NOT NULL,
    OPERATION          VARCHAR2(10)    NOT NULL,
    PRIMARY_KEY_VALUE  VARCHAR2(50),
    COLUMN_NAME        VARCHAR2(30),
    OLD_VALUE          VARCHAR2(4000),
    NEW_VALUE          VARCHAR2(4000),
    CHANGED_BY         VARCHAR2(30)    DEFAULT USER,
    CHANGED_DATE       DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_AUDIT PRIMARY KEY (AUDIT_ID)
);

-- Indexes
CREATE INDEX MFG.IDX_BOM_PARENT ON MFG.BILL_OF_MATERIALS (PARENT_PART_ID);
CREATE INDEX MFG.IDX_BOM_COMP ON MFG.BILL_OF_MATERIALS (COMPONENT_PART_ID);
CREATE INDEX MFG.IDX_INV_TXN_PART ON MFG.INVENTORY_TRANSACTIONS (PART_ID, TXN_DATE);
CREATE INDEX MFG.IDX_WARRANTY_VIN ON MFG.WARRANTY_CLAIMS (VIN);
CREATE INDEX MFG.IDX_WARRANTY_PART ON MFG.WARRANTY_CLAIMS (PART_ID);
CREATE INDEX MFG.IDX_INSP_PART ON MFG.QUALITY_INSPECTIONS (PART_ID);
CREATE INDEX MFG.IDX_AUDIT_TABLE ON MFG.AUDIT_TRAIL (TABLE_NAME, CHANGED_DATE);
CREATE INDEX MFG.IDX_PRODORD_STATUS ON MFG.PRODUCTION_ORDERS (STATUS, DUE_DATE);
