-- =============================================================================
-- Triggers — Oracle Database 19c
-- Oracle-isms: :NEW/:OLD, BEFORE/AFTER ROW, RAISE_APPLICATION_ERROR,
--              SYSDATE, USER, autonomous transaction in trigger
-- =============================================================================

-- Auto-populate PART_ID from sequence on insert
CREATE OR REPLACE TRIGGER MFG.TRG_PART_MASTER_BI
BEFORE INSERT ON MFG.PART_MASTER
FOR EACH ROW
BEGIN
    IF :NEW.PART_ID IS NULL THEN
        :NEW.PART_ID := MFG.PART_SEQ.NEXTVAL;
    END IF;
    :NEW.CREATED_DATE := NVL(:NEW.CREATED_DATE, SYSDATE);
    :NEW.MODIFIED_DATE := SYSDATE;
    :NEW.MODIFIED_BY := USER;
END;
/

-- Track cost changes on part master
CREATE OR REPLACE TRIGGER MFG.TRG_PART_COST_AUDIT
AFTER UPDATE OF CURRENT_COST ON MFG.PART_MASTER
FOR EACH ROW
WHEN (NVL(OLD.CURRENT_COST, 0) != NVL(NEW.CURRENT_COST, 0))
BEGIN
    INSERT INTO MFG.AUDIT_TRAIL (
        AUDIT_ID, TABLE_NAME, OPERATION, PRIMARY_KEY_VALUE,
        COLUMN_NAME, OLD_VALUE, NEW_VALUE, CHANGED_BY, CHANGED_DATE
    ) VALUES (
        MFG.AUDIT_SEQ.NEXTVAL, 'PART_MASTER', 'UPDATE',
        TO_CHAR(:NEW.PART_ID), 'CURRENT_COST',
        TO_CHAR(:OLD.CURRENT_COST), TO_CHAR(:NEW.CURRENT_COST),
        USER, SYSDATE
    );
END;
/

-- Auto-populate ORDER_ID and validate dates
CREATE OR REPLACE TRIGGER MFG.TRG_PROD_ORDER_BI
BEFORE INSERT ON MFG.PRODUCTION_ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        :NEW.ORDER_ID := MFG.ORDER_SEQ.NEXTVAL;
    END IF;

    IF :NEW.ORDER_NUMBER IS NULL THEN
        :NEW.ORDER_NUMBER := 'WO-' ||
            TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' ||
            LPAD(TO_CHAR(MFG.ORDER_SEQ.CURRVAL), 6, '0');
    END IF;

    IF :NEW.DUE_DATE < :NEW.ORDER_DATE THEN
        RAISE_APPLICATION_ERROR(-20010,
            'Due date cannot be before order date');
    END IF;

    :NEW.CREATED_DATE := SYSDATE;
END;
/

-- Prevent deletion of parts with active BOM references
CREATE OR REPLACE TRIGGER MFG.TRG_PART_DELETE_CHECK
BEFORE DELETE ON MFG.PART_MASTER
FOR EACH ROW
DECLARE
    v_ref_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_ref_count
    FROM   MFG.BILL_OF_MATERIALS
    WHERE  PARENT_PART_ID = :OLD.PART_ID
    OR     COMPONENT_PART_ID = :OLD.PART_ID;

    IF v_ref_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20011,
            'Cannot delete part ' || :OLD.PART_NUMBER ||
            ': referenced in ' || v_ref_count || ' BOM records');
    END IF;
END;
/

-- Auto-populate claim ID and default dates
CREATE OR REPLACE TRIGGER MFG.TRG_WARRANTY_CLAIM_BI
BEFORE INSERT ON MFG.WARRANTY_CLAIMS
FOR EACH ROW
BEGIN
    IF :NEW.CLAIM_ID IS NULL THEN
        :NEW.CLAIM_ID := MFG.CLAIM_SEQ.NEXTVAL;
    END IF;

    IF :NEW.CLAIM_NUMBER IS NULL THEN
        :NEW.CLAIM_NUMBER := 'CLM-' ||
            TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' ||
            LPAD(TO_CHAR(:NEW.CLAIM_ID), 6, '0');
    END IF;

    :NEW.CREATED_DATE := SYSDATE;
    :NEW.DISPOSITION := NVL(:NEW.DISPOSITION, 'PENDING');
END;
/

-- Update production order status based on completion
CREATE OR REPLACE TRIGGER MFG.TRG_PROD_ORDER_STATUS
BEFORE UPDATE OF COMPLETED_QTY ON MFG.PRODUCTION_ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.COMPLETED_QTY >= :NEW.ORDER_QTY THEN
        :NEW.STATUS := 'COMPLETED';
        :NEW.COMPLETION_DATE := NVL(:NEW.COMPLETION_DATE, SYSDATE);
    ELSIF :NEW.COMPLETED_QTY > 0 THEN
        :NEW.STATUS := 'IN_PROGRESS';
    END IF;
END;
/

-- Auto-populate inspection ID
CREATE OR REPLACE TRIGGER MFG.TRG_INSPECTION_BI
BEFORE INSERT ON MFG.QUALITY_INSPECTIONS
FOR EACH ROW
BEGIN
    IF :NEW.INSPECTION_ID IS NULL THEN
        :NEW.INSPECTION_ID := MFG.INSPECTION_SEQ.NEXTVAL;
    END IF;
    :NEW.CREATED_DATE := SYSDATE;
END;
/
